//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6400
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLIN_API_Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PLIN_API_Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLIN-API Example.
        /// </summary>
        internal static string SAppCaption {
            get {
                return ResourceManager.GetString("SAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLIN-API Example - Error.
        /// </summary>
        internal static string SAppCaptionError {
            get {
                return ResourceManager.GetString("SAppCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No hardware found&gt;.
        /// </summary>
        internal static string SHardwareNothingFound {
            get {
                return ResourceManager.GetString("SHardwareNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAN-USB Pro.
        /// </summary>
        internal static string SHardwareTypeLIN {
            get {
                return ResourceManager.GetString("SHardwareTypeLIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string SHardwareTypeUnkown {
            get {
                return ResourceManager.GetString("SHardwareTypeUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string SLinCSTAuto {
            get {
                return ResourceManager.GetString("SLinCSTAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string SLinCSTClassic {
            get {
                return ResourceManager.GetString("SLinCSTClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string SLinCSTCustom {
            get {
                return ResourceManager.GetString("SLinCSTCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced.
        /// </summary>
        internal static string SLinCSTEnhanced {
            get {
                return ResourceManager.GetString("SLinCSTEnhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Automatic Length.
        /// </summary>
        internal static string SLinDirectionAuto {
            get {
                return ResourceManager.GetString("SLinDirectionAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string SLinDirectionDisabled {
            get {
                return ResourceManager.GetString("SLinDirectionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string SLinDirectionPublisher {
            get {
                return ResourceManager.GetString("SLinDirectionPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber.
        /// </summary>
        internal static string SLinDirectionSubscriber {
            get {
                return ResourceManager.GetString("SLinDirectionSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus: Active.
        /// </summary>
        internal static string SLINStatusActive {
            get {
                return ResourceManager.GetString("SLINStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware: Baudrate Detection.
        /// </summary>
        internal static string SLINStatusBaudDetect {
            get {
                return ResourceManager.GetString("SLINStatusBaudDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware: Not Initialized.
        /// </summary>
        internal static string SLINStatusNotInit {
            get {
                return ResourceManager.GetString("SLINStatusNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus-Line: Shorted Ground.
        /// </summary>
        internal static string SLINStatusShortGround {
            get {
                return ResourceManager.GetString("SLINStatusShortGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus: Sleep.
        /// </summary>
        internal static string SLINStatusSleep {
            get {
                return ResourceManager.GetString("SLINStatusSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLIN_EXAMPLE.
        /// </summary>
        internal static string SPLinClientName {
            get {
                return ResourceManager.GetString("SPLinClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit.
        /// </summary>
        internal static string SWriteAsMaster {
            get {
                return ResourceManager.GetString("SWriteAsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string SWriteAsSlave {
            get {
                return ResourceManager.GetString("SWriteAsSlave", resourceCulture);
            }
        }
    }
}
