'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.6407
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PLIN_API_Example.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLIN-API Example.
        '''</summary>
        Friend ReadOnly Property SAppCaption() As String
            Get
                Return ResourceManager.GetString("SAppCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLIN-API Example - Error.
        '''</summary>
        Friend ReadOnly Property SAppCaptionError() As String
            Get
                Return ResourceManager.GetString("SAppCaptionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;No hardware found&gt;.
        '''</summary>
        Friend ReadOnly Property SHardwareNothingFound() As String
            Get
                Return ResourceManager.GetString("SHardwareNothingFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PCAN-USB Pro.
        '''</summary>
        Friend ReadOnly Property SHardwareTypeLIN() As String
            Get
                Return ResourceManager.GetString("SHardwareTypeLIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend ReadOnly Property SHardwareTypeUnkown() As String
            Get
                Return ResourceManager.GetString("SHardwareTypeUnkown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto.
        '''</summary>
        Friend ReadOnly Property SLinCSTAuto() As String
            Get
                Return ResourceManager.GetString("SLinCSTAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classic.
        '''</summary>
        Friend ReadOnly Property SLinCSTClassic() As String
            Get
                Return ResourceManager.GetString("SLinCSTClassic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom.
        '''</summary>
        Friend ReadOnly Property SLinCSTCustom() As String
            Get
                Return ResourceManager.GetString("SLinCSTCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enhanced.
        '''</summary>
        Friend ReadOnly Property SLinCSTEnhanced() As String
            Get
                Return ResourceManager.GetString("SLinCSTEnhanced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subscriber Automatic Length.
        '''</summary>
        Friend ReadOnly Property SLinDirectionAuto() As String
            Get
                Return ResourceManager.GetString("SLinDirectionAuto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled.
        '''</summary>
        Friend ReadOnly Property SLinDirectionDisabled() As String
            Get
                Return ResourceManager.GetString("SLinDirectionDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publisher.
        '''</summary>
        Friend ReadOnly Property SLinDirectionPublisher() As String
            Get
                Return ResourceManager.GetString("SLinDirectionPublisher", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subscriber.
        '''</summary>
        Friend ReadOnly Property SLinDirectionSubscriber() As String
            Get
                Return ResourceManager.GetString("SLinDirectionSubscriber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bus: Active.
        '''</summary>
        Friend ReadOnly Property SLINStatusActive() As String
            Get
                Return ResourceManager.GetString("SLINStatusActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardware: Baudrate Detection.
        '''</summary>
        Friend ReadOnly Property SLINStatusBaudDetect() As String
            Get
                Return ResourceManager.GetString("SLINStatusBaudDetect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardware: Not Initialized.
        '''</summary>
        Friend ReadOnly Property SLINStatusNotInit() As String
            Get
                Return ResourceManager.GetString("SLINStatusNotInit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bus-Line: Shorted Ground.
        '''</summary>
        Friend ReadOnly Property SLINStatusShortGround() As String
            Get
                Return ResourceManager.GetString("SLINStatusShortGround", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bus: Sleep.
        '''</summary>
        Friend ReadOnly Property SLINStatusSleep() As String
            Get
                Return ResourceManager.GetString("SLINStatusSleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLIN_EXAMPLE.
        '''</summary>
        Friend ReadOnly Property SPLinClientName() As String
            Get
                Return ResourceManager.GetString("SPLinClientName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmit.
        '''</summary>
        Friend ReadOnly Property SWriteAsMaster() As String
            Get
                Return ResourceManager.GetString("SWriteAsMaster", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Publish.
        '''</summary>
        Friend ReadOnly Property SWriteAsSlave() As String
            Get
                Return ResourceManager.GetString("SWriteAsSlave", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
