#ifndef MODELDATAMANAGE_GLOBAL_H
#define MODELDATAMANAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELDATAMANAGE_LIBRARY)
#  define MODELDATAMANAGE_EXPORT Q_DECL_EXPORT
#else
#  define MODELDATAMANAGE_EXPORT Q_DECL_IMPORT
#endif

#endif // MODELDATAMANAGE_GLOBAL_H
